### ISSUE TITLE
WIKI pages should open in new tab

### ISSUE THREAD

**Issue by rkrug** [OSGeo/grass-website#194] opened 2020-07-03 08:38 UTC
The link to the WIKI opens in the same tab. 

It would be nice, if pages from different websites, i.e. with a different design language and navigation system, could open in a new tab, especially as the back navigation can not be done from the website,  but the browser back-button needs to be used.

**Comment by veroandreo** [comment] 2020-07-03 14:30
Thanks for testing the new website. Since this problem is already reported, I'm closing it as a duplicate of #185. Please, keep testing :) Also PR are welcome!

**Closed by veroandreo** 2020-07-03 14:30 UTC
