### ISSUE TITLE
Write a decent 404.html

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#204] opened 2020-07-27 21:43 UTC
The current 404.html looks ... rather empty:

e.g.
https://grass.osgeo.org/blabla

![image](https://user-images.githubusercontent.com/1295172/88595207-d6f56400-d062-11ea-949b-58c281fb5dbd.png)

May we have a better one please, showing the user where to go? Thanks!

**Comment by veroandreo** [comment] 2020-07-28 00:29
I just found [here](https://gohugo.io/templates/404/) that HUGO provides a very basic template. We could in the meantime replace the content of `themes/grass/layouts/404.html` with the following

```
{{ define "main"}}
    <main id="main">
      <div>
       <h1 id="title"><a href="{{ "/" | relURL }}">Go Home</a></h1>
      </div>
    </main>
{{ end }}
```
until @nbozon helps us with something fancier :smiley_cat: 

Here's what academic provides for example: https://gitlab.com/veroandreo/veroandreo.gitlab.io/-/blob/master/themes/hugo-academic/layouts/404.html

**Comment by lucadelu** [comment] 2020-07-28 05:02
> I just found [here](https://gohugo.io/templates/404/) that HUGO provides a very basic template. We could in the meantime replace the content of `themes/grass/layouts/404.html` with the following
> 
> ```
> {{ define "main"}}
>     <main id="main">
>       <div>
>        <h1 id="title"><a href="{{ "/" | relURL }}">Go Home</a></h1>
>       </div>
>     </main>
> {{ end }}
> ```

Did it... but I was not able to test since if I look for a missing page hugo (using hugo server) return "404 page not found"

**Comment by neteler** [comment] 2020-07-28 06:28
In Apache, we have

```
grep ErrorDocument /etc/apache2/sites-enabled/000-default.conf 
ErrorDocument 404 /404.html
```

If I remove that, then I can the plain
```
Not Found

The requested URL was not found on this server.
```

With ErrorDocument active, it shows the content of https://grass.osgeo.org/404.html

**Comment by neteler** [comment] 2020-07-28 06:32
@lucadelu found it: you didn't push it to master!

This isn't updated yet:
https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/404.html

**Comment by lucadelu** [comment] 2020-07-28 08:04
> @lucadelu found it: you didn't push it to master!
> 
> This isn't updated yet:
> https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/404.html

I was speaking locally on my laptop. I know I didn't push to master (I forgot to open a PR)

**Comment by neteler** [comment] 2020-07-28 14:04
Well, the merge of #206 leads to a completely white page :-(

Try https://grass.osgeo.org/blabla

**Comment by neteler** [comment] 2020-07-29 15:38
> Well, the merge of #206 leads to a completely white page :-(

Do you have an idea, @nbozon @mlennert ?

> Try https://grass.osgeo.org/blabla

**Comment by mlennert** [comment] 2020-07-29 15:56
> > Well, the merge of #206 leads to a completely white page :-(
> 
> Do you have an idea, @nbozon @mlennert ?
> 
> > Try https://grass.osgeo.org/blabla

Looking into it.

**Comment by mlennert** [comment] 2020-07-29 16:28
Try #217. This seems to work for me locally in an Apache setting.

**Comment by nbozon** [comment] 2020-07-29 16:46
I also have it working locally, with partials included 
Would that do the trick ?
<img width="649" alt="404" src="https://user-images.githubusercontent.com/7135374/88828014-edb6ca80-d1ca-11ea-97dd-4ff2cad8dc3a.png">

**Comment by neteler** [comment] 2020-07-29 18:58
Looks good to me!

**Comment by mlennert** [comment] 2020-07-29 19:11
Am 29. Juli 2020 18:47:00 MESZ schrieb Nicolas Bozon <notifications@github.com>:
>I also have it working locally, with partials included 
>Would that do the trick ?

Looks very good to me !

Moritz


><img width="449" alt="404"
>src="https://user-images.githubusercontent.com/7135374/88828014-edb6ca80-d1ca-11ea-97dd-4ff2cad8dc3a.png">

**Comment by neteler** [comment] 2020-07-30 07:07
Please merge...

**Comment by mlennert** [comment] 2020-07-31 10:29
I would actually say that @nbozon 's solution looks much nicer ;-). As it already exists, I will not spend time now trying to reproduce, but hope that Nick will commit, soon.

**Comment by nbozon** [comment] 2020-09-13 07:45
[Added to master]( https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/404.html)!
Please see: https://grass.osgeo.org/blabla 
Closing this one -

**Closed by nbozon** 2020-09-13 07:45 UTC
